services:
  db:
    image: postgres:18-alpine
    container_name: postgres_db
    shm_size: 128mb
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "9090:8080"
    depends_on:
      - db

volumes:
  postgres_data:
