[project]
name = "finview-backend"
version = "0.1.0"
description = "Finary-like"
authors = [
    {name = "blueh0rse",email = "110935049+blueh0rse@users.noreply.github.com"}
]
readme = "README.md"
requires-python = "==3.12.*"

dependencies = [
    "alembic>=1.17.1",
    "fastapi[standard] (>=0.119.1,<0.120.0)",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.1.1",
    "sqlalchemy>=2.0.44",
    "uvicorn[standard]>=0.38.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.14.1",
]

[tool.ruff]
exclude = [
    "scripts/*",
    "src/api/db/models.py",
    "src/migrations/*",
]
